favicon: https://cdn.jsdelivr.net/gh/hassanblog/CDN@v20210405/navi/favicon.ico
banner: https://cdn.jsdelivr.net/gh/hassanblog/CDN@v20210405/navi/webstack_banner_cn.png

logo:
  expanded: https://cdn.jsdelivr.net/gh/hassanblog/CDN@v20210405/navi/logo@2x.png
  collapsed: https://cdn.jsdelivr.net/gh/hassanblog/CDN@v20210405/navi/logo-collapsed@2x.png
  dark: https://cdn.jsdelivr.net/gh/hassanblog/CDN@v20210405/navi/logo_dark@2x.png

flag:
  icon: flag-cn
  name: China

search: true

githubCorner: '<a href="https://github.com/hassanblog/navigation" class="github-corner" aria-label="View source on GitHub"><svg width="66" height="66" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: 与我相关
    icon: far fa-star
    submenu:
      - name: 博客常用
        icon: iconfont icon-blog
        config: 博客常用
      - name: 社交平台
        icon: iconfont icon-social
        config: 社交平台
  - name: 学习
    icon: iconfont icon-study
    submenu:
      - name: 大学常用
        icon: iconfont icon-book
        config: 大学常用
      - name: 英语雅思
        icon: iconfont icon-english
        config: 英语雅思
  - name: 编程
    icon: iconfont icon-code
    config: 编程
  - name: 前端
    icon: iconfont icon-cherry
    config: 前端
  - name: 视图文素材
    icon: iconfont icon-video
    config: 视图文素材
  - name: 工具
    icon: fas fa-tools
    submenu:
      - name: 图片
        icon: iconfont icon-photo
        config: 图片
      - name: 其他
        icon: iconfont icon-about
        config: 其他
  - name: 音乐
    icon: iconfont icon-music
    config: 音乐
  - name: 友链
    icon: iconfont icon-blogroll
    config: 友链

about:
  url: /about_website/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是由<a href="https://github.com/hassanblog">Hassan Wong</a>基于<a href="https://hexo.io/">Hexo框架</a>主题为<a href="https://github.com/HCLonely/hexo-theme-webstack">WebStack</a>所搭建的。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: Hassan Wong
    url: https://hassanwong.top
    img: https://cdn.jsdelivr.net/gh/hassanblog/CDN@v20210405/navi/logos/myblog.png
    description: 时不我待，只争朝夕
    html: ""

since: 2021

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <link rel="stylesheet" type="text/css" href="/css/custom.css">
    <link rel="stylesheet" type="text/css" href="//at.alicdn.com/t/font_2204525_az7e3ucr4x.css">
  body: # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <div class="bg"></div>
    <script src="/js/custom.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/lozad.min.js"></script>
js:
  header: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/header.js
  footer: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/footer.js
  jquery: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/jquery-1.11.1.min.js
  bootstrap: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/bootstrap.min.js
  TweenMax: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/TweenMax.min.js
  resizeable: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/resizeable.min.js
  joinable: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/joinable.js
  xenonApi: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/xenon-api.min.js
  xenonToggles: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/xenon-toggles.min.js
  xenonCustom: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/xenon-custom.min.js
  lozad: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/lozad.min.js
  html5shiv: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/html5shiv.min.js
  respond: https://cdn.jsdelivr.net/gh/hassanblog/navigation/js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: https://cdn.jsdelivr.net/gh/hassanblog/navigation/css/hclonely.css
  linecons: https://cdn.jsdelivr.net/gh/hassanblog/navigation/css/fonts/linecons/css/linecons.min.css
  fontawesome: https://cdn.jsdelivr.net/gh/hassanblog/navigation/css/fonts/fontawesome/css/all.min.css
  bootstrap: https://cdn.jsdelivr.net/gh/hassanblog/navigation/css/bootstrap.min.css
  xenonCore: https://cdn.jsdelivr.net/gh/hassanblog/navigation/css/xenon-core.min.css
  xenonComponents: https://cdn.jsdelivr.net/gh/hassanblog/navigation/css/xenon-components.min.css
  xenonSkins: https://cdn.jsdelivr.net/gh/hassanblog/navigation/css/xenon-skins.min.css
  nav: https://cdn.jsdelivr.net/gh/hassanblog/navigation/css/nav.min.css
